FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Créer le répertoire pour les données
RUN mkdir -p /app/data && cp /app/lib/product.json /app/data/product.json || true

EXPOSE 3000

CMD ["npm", "start"]
